backend:
  name: git-gateway
  branch: master

publish_mode: "editorial_workflow"
media_folder: "/static/images"
public_folder: "/images"

collections:
  - name: "bulletins"
    label: "Bulletins"
    folder: "content/bulletins"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "bulletin"}
      - {label: "Date", name: "date", widget: "datetime", timeFormat: false}
      - label: "Events"
        name: "events"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Date", name: "date", widget: "datetime", timeFormat: false}
          - {label: "Time", name: "time", widget: "datetime", dateFormat: false}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Link", name: "link", widget: "string"}